from __future__ import annotations

from enum import StrEnum


class CommandName(StrEnum):
    ASK = "ask"
    CHAT = "chat"
    EVALUATE = "evaluate"
    EVALUATE_ANSWERS = "evaluate-answers"
    EVALUATE_EXPLANATIONS = "evaluate-explanations"
    EVALUATE_INDEXING = "evaluate-indexing"
    EVALUATE_SEARCH_TOOLS = "evaluate-search-tools"
    EXPERIMENT = "experiment"
    GREP = "grep"
    INIT = "init"
    INDEX = "index"
    INDEX_SELECTED = "index-selected"
    MONITOR = "monitor"
    OPEN = "open"
    PROVIDER = "provider"
    READ = "read"
    RG = "rg"
    SEARCH = "search"
    SYMBOLS = "symbols"
    TREE = "tree"


class OptionName(StrEnum):
    APPEND_SYSTEM_PROMPT = "--append-system-prompt"
    BENCHMARK = "--benchmark"
    CONFIG = "--config"
    DATASET = "--dataset"
    DETAILS = "--details"
    EXTENSION = "--extension"
    HELP_ALL = "--help-all"
    HYPOTHESIS = "--hypothesis"
    JSON = "--json"
    LIMIT = "--limit"
    MODEL = "--model"
    NAME = "--name"
    PATH = "--path"
    PRINT = "-p"
    PROMPT_TEMPLATE = "--prompt-template"
    PROVIDER = "--provider"
    RANK = "--rank"
    REINDEX = "--reindex"
    ROOT = "--root"
    SESSION = "--session"
    SESSION_DIR = "--session-dir"
    SESSION_ID = "--session-id"
    START_LINE = "--start-line"
    TOOLSET = "--toolset"
    TOOLS = "--tools"
    LINES = "--lines"
    YES = "--yes"
