from __future__ import annotations

from enum import StrEnum


class EnvironmentVariable(StrEnum):
    CODE_DIVER_CONFIG = "CODE_DIVER_CONFIG"
    CODE_DIVER_QDRANT_COLLECTION = "CODE_DIVER_QDRANT_COLLECTION"
    CODE_DIVER_ROOT = "CODE_DIVER_ROOT"
    EDITOR = "EDITOR"
    GEMINI_API_KEY = "GEMINI_API_KEY"
    GOOGLE_CLOUD_LOCATION = "GOOGLE_CLOUD_LOCATION"
    GOOGLE_CLOUD_PROJECT = "GOOGLE_CLOUD_PROJECT"
    CODE_DIVER_VERTEX_BATCH_GCS_URI = "CODE_DIVER_VERTEX_BATCH_GCS_URI"
    OPENAI_API_KEY = "OPENAI_API_KEY"
