# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import code_diver_pb2 as code__diver__pb2
except ImportError:
    import code_diver_pb2 as code__diver__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in code_diver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeDiverServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/codediver.v1.CodeDiverService/Search',
                request_serializer=code__diver__pb2.SearchRequest.SerializeToString,
                response_deserializer=code__diver__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/codediver.v1.CodeDiverService/Info',
                request_serializer=code__diver__pb2.InfoRequest.SerializeToString,
                response_deserializer=code__diver__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.ReadExcerpt = channel.unary_unary(
                '/codediver.v1.CodeDiverService/ReadExcerpt',
                request_serializer=code__diver__pb2.ReadExcerptRequest.SerializeToString,
                response_deserializer=code__diver__pb2.ReadExcerptResponse.FromString,
                _registered_method=True)
        self.Grep = channel.unary_unary(
                '/codediver.v1.CodeDiverService/Grep',
                request_serializer=code__diver__pb2.GrepRequest.SerializeToString,
                response_deserializer=code__diver__pb2.GrepResponse.FromString,
                _registered_method=True)
        self.Symbols = channel.unary_unary(
                '/codediver.v1.CodeDiverService/Symbols',
                request_serializer=code__diver__pb2.SymbolsRequest.SerializeToString,
                response_deserializer=code__diver__pb2.SymbolsResponse.FromString,
                _registered_method=True)
        self.Tree = channel.unary_unary(
                '/codediver.v1.CodeDiverService/Tree',
                request_serializer=code__diver__pb2.TreeRequest.SerializeToString,
                response_deserializer=code__diver__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.TriggerIndex = channel.unary_stream(
                '/codediver.v1.CodeDiverService/TriggerIndex',
                request_serializer=code__diver__pb2.IndexRequest.SerializeToString,
                response_deserializer=code__diver__pb2.IndexProgressUpdate.FromString,
                _registered_method=True)
        self.IngestFiles = channel.stream_unary(
                '/codediver.v1.CodeDiverService/IngestFiles',
                request_serializer=code__diver__pb2.IngestFileChunk.SerializeToString,
                response_deserializer=code__diver__pb2.IngestSummary.FromString,
                _registered_method=True)


class CodeDiverServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadExcerpt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Grep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Symbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFiles(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeDiverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=code__diver__pb2.SearchRequest.FromString,
                    response_serializer=code__diver__pb2.SearchResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=code__diver__pb2.InfoRequest.FromString,
                    response_serializer=code__diver__pb2.InfoResponse.SerializeToString,
            ),
            'ReadExcerpt': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadExcerpt,
                    request_deserializer=code__diver__pb2.ReadExcerptRequest.FromString,
                    response_serializer=code__diver__pb2.ReadExcerptResponse.SerializeToString,
            ),
            'Grep': grpc.unary_unary_rpc_method_handler(
                    servicer.Grep,
                    request_deserializer=code__diver__pb2.GrepRequest.FromString,
                    response_serializer=code__diver__pb2.GrepResponse.SerializeToString,
            ),
            'Symbols': grpc.unary_unary_rpc_method_handler(
                    servicer.Symbols,
                    request_deserializer=code__diver__pb2.SymbolsRequest.FromString,
                    response_serializer=code__diver__pb2.SymbolsResponse.SerializeToString,
            ),
            'Tree': grpc.unary_unary_rpc_method_handler(
                    servicer.Tree,
                    request_deserializer=code__diver__pb2.TreeRequest.FromString,
                    response_serializer=code__diver__pb2.TreeResponse.SerializeToString,
            ),
            'TriggerIndex': grpc.unary_stream_rpc_method_handler(
                    servicer.TriggerIndex,
                    request_deserializer=code__diver__pb2.IndexRequest.FromString,
                    response_serializer=code__diver__pb2.IndexProgressUpdate.SerializeToString,
            ),
            'IngestFiles': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestFiles,
                    request_deserializer=code__diver__pb2.IngestFileChunk.FromString,
                    response_serializer=code__diver__pb2.IngestSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codediver.v1.CodeDiverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codediver.v1.CodeDiverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeDiverService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/Search',
            code__diver__pb2.SearchRequest.SerializeToString,
            code__diver__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/Info',
            code__diver__pb2.InfoRequest.SerializeToString,
            code__diver__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadExcerpt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/ReadExcerpt',
            code__diver__pb2.ReadExcerptRequest.SerializeToString,
            code__diver__pb2.ReadExcerptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Grep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/Grep',
            code__diver__pb2.GrepRequest.SerializeToString,
            code__diver__pb2.GrepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Symbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/Symbols',
            code__diver__pb2.SymbolsRequest.SerializeToString,
            code__diver__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codediver.v1.CodeDiverService/Tree',
            code__diver__pb2.TreeRequest.SerializeToString,
            code__diver__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codediver.v1.CodeDiverService/TriggerIndex',
            code__diver__pb2.IndexRequest.SerializeToString,
            code__diver__pb2.IndexProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFiles(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/codediver.v1.CodeDiverService/IngestFiles',
            code__diver__pb2.IngestFileChunk.SerializeToString,
            code__diver__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
