# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import mcp_service_pb2 as mcp__service__pb2
except ImportError:
    import mcp_service_pb2 as mcp__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MCPServiceStub:
    """Generic MCP Service Interface
    This can be implemented by any MCP service (memory, api, etc.)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/mcp.service.v1.MCPService/ListTools',
                request_serializer=mcp__service__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=mcp__service__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/mcp.service.v1.MCPService/CallTool',
                request_serializer=mcp__service__pb2.CallToolRequest.SerializeToString,
                response_deserializer=mcp__service__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/mcp.service.v1.MCPService/GetHealth',
                request_serializer=mcp__service__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=mcp__service__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/mcp.service.v1.MCPService/GetCapabilities',
                request_serializer=mcp__service__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=mcp__service__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)


class MCPServiceServicer:
    """Generic MCP Service Interface
    This can be implemented by any MCP service (memory, api, etc.)
    """

    def ListTools(self, request, context):
        """List available tools for this service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Call a tool directly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Get service health and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Get service metadata and capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MCPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=mcp__service__pb2.ListToolsRequest.FromString,
                    response_serializer=mcp__service__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mcp__service__pb2.CallToolRequest.FromString,
                    response_serializer=mcp__service__pb2.CallToolResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=mcp__service__pb2.GetHealthRequest.FromString,
                    response_serializer=mcp__service__pb2.GetHealthResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=mcp__service__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=mcp__service__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.service.v1.MCPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.service.v1.MCPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MCPService:
    """Generic MCP Service Interface
    This can be implemented by any MCP service (memory, api, etc.)
    """

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.service.v1.MCPService/ListTools',
            mcp__service__pb2.ListToolsRequest.SerializeToString,
            mcp__service__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.service.v1.MCPService/CallTool',
            mcp__service__pb2.CallToolRequest.SerializeToString,
            mcp__service__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.service.v1.MCPService/GetHealth',
            mcp__service__pb2.GetHealthRequest.SerializeToString,
            mcp__service__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.service.v1.MCPService/GetCapabilities',
            mcp__service__pb2.GetCapabilitiesRequest.SerializeToString,
            mcp__service__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
