#!/usr/bin/env python3
"""Test script for verifying scanner updates (line_count // 4) and rank-ordered excerpts.

1. Reindexes rust_bakery_nom in .benchmarks/repoqa/rust/rust_bakery_nom.
2. Checks needle 3 (test_offset_u8 in src/traits.rs):
   - Vector rank of src/traits.rs
   - Excerpts generated by build_agent_context (check if test_offset_u8 appears in excerpt/symbol outline)
   - Closed-loop agent run (Hit@1 check)
3. Tests junegunn/fzf needle 4 (processExecution in src/terminal.go) and
   tokio-rs/tracing needle 2 (as_ref in field.rs) with rank-ordered excerpts.
"""

from __future__ import annotations

import gzip
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from code_diver.cli import make_embedding_provider, make_vector_store
from code_diver.config import ConfigLoader
from code_diver.strategies.retrieval_strategy_factory import RetrievalStrategyFactory
from scripts.benchmark_repoqa import dedupe_files, index_repo, normalize_path
from scripts.benchmark_repoqa_agent_litellm import (
    DEFAULT_ENDPOINT,
    build_agent_context,
    evaluate_needle_closed_loop,
)


def load_dataset() -> dict[str, Any]:
    dataset_path = PROJECT_ROOT / "artifacts" / "repoqa" / "repoqa.json.gz"
    with gzip.open(dataset_path, "rt", encoding="utf-8") as f:
        return json.load(f)


def test_nom_reindex_and_needle3(base_cfg: Any, dataset: dict[str, Any], model: str, api_key: str) -> dict[str, Any]:
    print("\n" + "=" * 80)
    print("STEP 1 & 2: REINDEXING `rust-bakery/nom` & TESTING NEEDLE 3 (test_offset_u8)")
    print("=" * 80)

    nom_dir = (PROJECT_ROOT / ".benchmarks/repoqa/rust/rust_bakery_nom").resolve()
    print(f"Target repository path: {nom_dir}")

    # Step 1: Reindex with reindex=True
    t0 = time.perf_counter()
    config, idx_time = index_repo(
        target_dir=nom_dir,
        base_config=base_cfg,
        symbol_chunks=True,
        symbol_body=True,
        reindex=True,
        max_input_chars=1200,
    )
    print(f"Re-indexing complete in {time.perf_counter() - t0:.2f}s.")

    # Initialize retrieval strategy
    vs = make_vector_store(config)
    provider = make_embedding_provider(config, vs.metadata())
    strategy = RetrievalStrategyFactory().create("vector", config, provider, vs)

    # Locate needle 3
    nom_repo = next(r for r in dataset["rust"] if r["repo"] == "rust-bakery/nom")
    needle3 = nom_repo["needles"][3]
    query = needle3["description"].strip()
    target_file = normalize_path(needle3["path"])
    target_symbol = needle3.get("name")
    print(f"\nTarget File  : {target_file}")
    print(f"Target Symbol: {target_symbol}")
    print(f"Target Lines : {needle3.get('start_line')}-{needle3.get('end_line')}")

    # Vector search
    search_results = strategy.search(query, limit=25)
    retrieved_paths = [r.item.path for r in search_results]
    candidate_files = dedupe_files(retrieved_paths)
    vector_rank = candidate_files.index(target_file) + 1 if target_file in candidate_files else None

    print(f"\nVector Rank of `{target_file}`: #{vector_rank}")
    print(f"Top 5 Candidate Files: {candidate_files[:5]}")

    # Inspect hits for traits.rs
    traits_hits = [r for r in search_results if normalize_path(r.item.path) == target_file]
    print(f"\nRetrieved {len(traits_hits)} hits for {target_file}:")
    for idx, h in enumerate(traits_hits[:5], 1):
        print(f"  Hit #{idx}: score={h.score:.4f}, start_line={h.item.start_line}, title={h.item.title}")

    # Step 2: Context generation
    inspect_candidates = candidate_files[:8]
    context_text, inspect_ms = build_agent_context(
        repo_root=nom_dir,
        candidate_files=inspect_candidates,
        retrieved_items=search_results,
        max_symbols_per_file=120,
        max_excerpt_lines=60,
    )

    # Check outline & excerpt appearance
    blocks = context_text.split("### File: ")
    traits_block = next((b for b in blocks if target_file in b), "")

    has_symbol_in_outline = False
    has_symbol_in_excerpt = False
    if "Key Symbols:" in traits_block:
        parts = traits_block.split("Key Symbols:")[1].split("--- Excerpt")
        outline_part = parts[0]
        excerpt_part = ("--- Excerpt" + parts[1]) if len(parts) > 1 else ""
        has_symbol_in_outline = target_symbol in outline_part
        has_symbol_in_excerpt = target_symbol in excerpt_part
    else:
        outline_part = ""
        excerpt_part = ""

    print(f"\nContext Generation Analysis for `{target_file}`:")
    print(f"  Does `{target_symbol}` appear in symbol outline? {has_symbol_in_outline}")
    print(f"  Does `{target_symbol}` appear in code excerpt?    {has_symbol_in_excerpt}")

    print("\n--- Excerpts generated for `src/traits.rs` ---")
    if excerpt_part:
        for line in excerpt_part.strip().splitlines()[:30]:
            print("  " + line)
        if len(excerpt_part.strip().splitlines()) > 30:
            print("  ... [truncated for display]")
    else:
        print("  (no excerpt)")

    # Run the agent on needle 3
    print(f"\nRunning agent ({model}) on needle 3...")
    eval_res = evaluate_needle_closed_loop(
        needle=needle3,
        needle_index=3,
        strategy=strategy,
        repo_root=nom_dir,
        model=model,
        endpoint=DEFAULT_ENDPOINT,
        api_key=api_key,
        limit=25,
        max_inspect_files=8,
        max_symbols_per_file=120,
        max_excerpt_lines=60,
    )

    print(f"\nAgent Result for Needle 3:")
    print(f"  File Hit@1     : {eval_res['file_hit1']}")
    print(f"  Exact Line Hit : {eval_res['exact_line_hit']}")
    print(f"  Agent Top File : {eval_res['final_ranked_files'][0] if eval_res['final_ranked_files'] else None}")
    print(f"  Agent Best Match: {eval_res['agent_best_match']}")
    print(f"  Agent Reasoning: {eval_res['reasoning']}")

    return {
        "vector_rank": vector_rank,
        "has_symbol_in_outline": has_symbol_in_outline,
        "has_symbol_in_excerpt": has_symbol_in_excerpt,
        "eval_res": eval_res,
        "excerpt_sample": excerpt_part[:500],
    }


def test_fzf_needle4_and_tracing_needle2(base_cfg: Any, dataset: dict[str, Any], model: str, api_key: str) -> dict[str, Any]:
    print("\n" + "=" * 80)
    print("STEP 3: TESTING junegunn/fzf NEEDLE 4 & tokio-rs/tracing NEEDLE 2")
    print("=" * 80)

    results = {}

    # 1. junegunn/fzf needle 4
    print("\n--- Testing `junegunn/fzf` Needle 4 (`processExecution` in `src/terminal.go`) ---")
    fzf_dir = (PROJECT_ROOT / ".benchmarks/repoqa/go/junegunn_fzf").resolve()
    cfg_fzf, _ = index_repo(fzf_dir, base_cfg, symbol_chunks=True, symbol_body=True, reindex=False, max_input_chars=1200)
    vs_fzf = make_vector_store(cfg_fzf)
    prov_fzf = make_embedding_provider(cfg_fzf, vs_fzf.metadata())
    strat_fzf = RetrievalStrategyFactory().create("vector", cfg_fzf, prov_fzf, vs_fzf)

    fzf_repo = next(r for r in dataset["go"] if r["repo"] == "junegunn/fzf")
    n4 = fzf_repo["needles"][4]

    eval_fzf = evaluate_needle_closed_loop(
        needle=n4,
        needle_index=4,
        strategy=strat_fzf,
        repo_root=fzf_dir,
        model=model,
        endpoint=DEFAULT_ENDPOINT,
        api_key=api_key,
        limit=25,
        max_inspect_files=8,
        max_symbols_per_file=120,
        max_excerpt_lines=60,
    )
    print(f"  Target File    : {eval_fzf['target_file']}")
    print(f"  File Hit@1     : {eval_fzf['file_hit1']}")
    print(f"  Exact Line Hit : {eval_fzf['exact_line_hit']}")
    print(f"  Agent Top File : {eval_fzf['final_ranked_files'][0] if eval_fzf['final_ranked_files'] else None}")
    print(f"  Agent Best Match: {eval_fzf['agent_best_match']}")
    print(f"  Agent Reasoning: {eval_fzf['reasoning']}")
    results["fzf"] = eval_fzf

    # 2. tokio-rs/tracing needle 2
    print("\n--- Testing `tokio-rs/tracing` Needle 2 (`as_ref` in `field.rs`) ---")
    tr_dir = (PROJECT_ROOT / ".benchmarks/repoqa/rust/tokio_rs_tracing").resolve()
    cfg_tr, _ = index_repo(tr_dir, base_cfg, symbol_chunks=True, symbol_body=True, reindex=False, max_input_chars=1200)
    vs_tr = make_vector_store(cfg_tr)
    prov_tr = make_embedding_provider(cfg_tr, vs_tr.metadata())
    strat_tr = RetrievalStrategyFactory().create("vector", cfg_tr, prov_tr, vs_tr)

    tr_repo = next(r for r in dataset["rust"] if r["repo"] == "tokio-rs/tracing")
    n2 = tr_repo["needles"][2]

    eval_tr = evaluate_needle_closed_loop(
        needle=n2,
        needle_index=2,
        strategy=strat_tr,
        repo_root=tr_dir,
        model=model,
        endpoint=DEFAULT_ENDPOINT,
        api_key=api_key,
        limit=25,
        max_inspect_files=8,
        max_symbols_per_file=120,
        max_excerpt_lines=60,
    )
    print(f"  Target File    : {eval_tr['target_file']}")
    print(f"  File Hit@1     : {eval_tr['file_hit1']}")
    print(f"  Exact Line Hit : {eval_tr['exact_line_hit']}")
    print(f"  Agent Top File : {eval_tr['final_ranked_files'][0] if eval_tr['final_ranked_files'] else None}")
    print(f"  Agent Best Match: {eval_tr['agent_best_match']}")
    print(f"  Agent Reasoning: {eval_tr['reasoning']}")
    results["tracing"] = eval_tr

    return results


def main() -> int:
    api_key = os.environ.get("LITE_LLM_KEY", "")
    if not api_key:
        print("Error: LITE_LLM_KEY is not set!", file=sys.stderr)
        return 1

    model = sys.argv[1] if len(sys.argv) > 1 else "gemini-3.5-flash-lite"
    print(f"Using LiteLLM model: {model}")

    base_cfg = ConfigLoader().load(None)
    dataset = load_dataset()

    nom_res = test_nom_reindex_and_needle3(base_cfg, dataset, model, api_key)
    other_res = test_fzf_needle4_and_tracing_needle2(base_cfg, dataset, model, api_key)

    print("\n" + "=" * 80)
    print(f"SUMMARY OF RESULTS ({model})")
    print("=" * 80)
    print(f"1. rust-bakery/nom needle 3 (`test_offset_u8` in `src/traits.rs`):")
    print(f"   - Vector rank of src/traits.rs: #{nom_res['vector_rank']}")
    print(f"   - Appears in symbol outline   : {nom_res['has_symbol_in_outline']}")
    print(f"   - Appears in code excerpt     : {nom_res['has_symbol_in_excerpt']}")
    print(f"   - Agent Hit@1                 : {nom_res['eval_res']['file_hit1']}")
    print(f"   - Exact Line Hit              : {nom_res['eval_res']['exact_line_hit']}")

    print(f"\n2. junegunn/fzf needle 4 (`processExecution` in `src/terminal.go`):")
    print(f"   - Agent Hit@1                 : {other_res['fzf']['file_hit1']}")
    print(f"   - Exact Line Hit              : {other_res['fzf']['exact_line_hit']}")
    print(f"   - Agent Top File              : {other_res['fzf']['final_ranked_files'][0] if other_res['fzf']['final_ranked_files'] else None}")

    print(f"\n3. tokio-rs/tracing needle 2 (`as_ref` in `field.rs`):")
    print(f"   - Agent Hit@1                 : {other_res['tracing']['file_hit1']}")
    print(f"   - Exact Line Hit              : {other_res['tracing']['exact_line_hit']}")
    print(f"   - Agent Top File              : {other_res['tracing']['final_ranked_files'][0] if other_res['tracing']['final_ranked_files'] else None}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
