apiVersion: 1

datasources:
  - name: Code Diver ClickHouse
    uid: code-diver-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: code_diver
      defaultDatabase: code_diver
      dialTimeout: 10
      queryTimeout: 60
      validateSql: true
      enableRowLimit: true
    secureJsonData:
      password: code_diver
